hosts:
  "larise live web": # host alias
    hostname: www.larise.com
    remote_user: medani
    identity_file: ~/.ssh/id_rsa_larise # use this ssh-key to connect to this server
    port: 222
    labels:
      type: web
      env: prod
  "larise live db":
    hostname: www.larise.com
    remote_user: medani_sql
    port: 222
    labels:
      type: db
      env: prod
  dev3.ps:
    hostname: dev3.ps.medani.at  
    remote_user: ben
    port: 22 # wouldn\'t be necessary here because it is the standard port
    labels:
      type: web
      env: dev
  dev3.db:
    hostname: dev3.db.medani.at  
    remote_user: ben
    labels:
      type: db
      env: dev